# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Logo Image Source
logo_src: images/panda_icon.png

# Theme Main Subtitle
subtitle_main: This is an Electrical Hardware and Software blog.

# Theme Secondary subtitle
susbtitle_secondary: Here is documentation for the projects I've worked on, tutorials and code snippets, and notes about projects and ideas that I'm working on.

# Footer About Section
about_footer: This page's source code is available on <a href="https://gitlab.com/j-mcavoy/blog" target="_blank">GitLab</a>. &copy; John McAvoy. All rights reserved

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: /images/place_holders/index.png

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates: true

# Social Accounts
gitlab_url: https://gitlab.com/j-mcavoy/
github_url: https://github.com/j-mcavoy/
linkedin_url: http://linkedin.com/in/john-mcavoy-8b888b183
email_url: mailto:j-mcavoy
website_url: https://j-mcavoy.gitlab.io/
rss_url: /rss.xml
